apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  labels:
    app: postgres
type: Opaque
data:
  POSTGRES_DB: ZGVtbw==
  #postgres-root-username: bmlraXRh
  postgres-root-password: ODkxOTc3OTE4MzZBYSE=
stringData:
  postgres-root-username: nikita