apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: minikube-service-account-token-access
  namespace: kube-system
subjects:
  - kind: ServiceAccount
    name: minikube
    namespace: kube-system
roleRef:
  kind: Role
  name: kube-proxy  # Or another role that provides the necessary permissions
  apiGroup: rbac.authorization.k8s.io