apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.short-app.name }}-deployment
  namespace: {{ .Values.short-app.namespace }}
spec:
  replicas: {{ .Values.short-app.replicas }}
  selector:
    matchLabels:
      components: {{ .Values.short-app.components }}
  template:
    metadata:
      labels:
        components: {{ .Values.short-app.components }}
    spec:
      containers:
      - name: {{ .Values.short-app.name }}
        image: "{{ .Values.short-app.image }}:{{ .Values.short-app.image_version }}"
        imagePullPolicy: Always
        resources:
          limits:
            memory: {{ .Values.short-app.limits.memory }}
            cpu: {{ .Values.short-app.limits.cpu }}
        ports:
          - containerPort: {{ .Values.short-app.containerPort }}
