apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.shortApp.name }}-clusterip
  namespace: {{ .Values.shortApp.namespace }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.shortApp.containerPort }}
      targetPort: {{ .Values.shortApp.containerPort }}
      protocol: TCP
  selector:
    components: {{ .Values.shortApp.components }}
