apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.shortApp.name }}-deployment
  namespace: {{ .Values.shortApp.namespace }}
spec:
  replicas: {{ .Values.shortApp.replicas }}
  selector:
    matchLabels:
      components: {{ .Values.shortApp.components }}
  template:
    metadata:
      labels:
        components: {{ .Values.shortApp.components }}
    spec:
      containers:
      - name: {{ .Values.shortApp.name }}
        image: "{{ .Values.shortApp.image }}:{{ .Values.shortApp.image_version }}"
        imagePullPolicy: Always
        resources:
          limits:
            {{ .Values.shortApp.limits | toYaml | nindent 14}}
            
        ports:
          - containerPort: {{ .Values.shortApp.containerPort }}

# toYml
# nintent