apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.short-app.name }}-clusterip
  namespace: {{ .Values.short-app.namespace }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.short-app.containerPort }}
      targetPort: {{ .Values.short-app.containerPort }}
      protocol: TCP
  selector:
    components: {{ .Values.short-app.components }}
