apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-config
data:
  key: {{ .Release.Name }}
  #name: {{ .Values.name | upper | quote }}
  chart: {{ .Chart.AppVersion | quote }}
  date: {{ now | date "2005-01-02" | quote }}