apiVersion: v1
kind: Service
metadata:
  name: pgadmin-clusterip
  labels:
    app: pgadmin
spec:
  type: ClusterIP
  ports:
    - name: admin
      protocol: TCP
      port: 30200
      targetPort: 80
  selector:
    app: pgadmin

