apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  labels:
    app: postgres
type: Opaque
data:
    postgres-root-username: bmlraXRh
    postgres-root-password: ODkxOTc3OTE4MzZBYSE
    POSTGRES_DB: ZGVtbw==